ALTER TABLE user_matches
    ADD COLUMN score_computed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE user_matches
    ADD CONSTRAINT uk_user_matches_pair UNIQUE (user_id, matched_user_id);

CREATE TABLE study_groups (
    group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name VARCHAR(255) NOT NULL,
    description TEXT,
    visibility VARCHAR(32) NOT NULL,
    owner_user_id BIGINT NOT NULL,
    primary_course VARCHAR(255),
    created_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_study_groups_owner FOREIGN KEY (owner_user_id) REFERENCES users (user_id)
);

CREATE INDEX idx_study_groups_owner ON study_groups (owner_user_id);
CREATE INDEX idx_study_groups_visibility ON study_groups (visibility);

CREATE TABLE study_group_members (
    group_member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    member_role VARCHAR(32) NOT NULL,
    joined_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_study_group_members_group FOREIGN KEY (group_id) REFERENCES study_groups (group_id),
    CONSTRAINT fk_study_group_members_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT uk_group_member_group_user UNIQUE (group_id, user_id)
);

CREATE INDEX idx_study_group_members_group ON study_group_members (group_id);
CREATE INDEX idx_study_group_members_user ON study_group_members (user_id);

CREATE TABLE study_group_invitations (
    invitation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    invited_by_user_id BIGINT NOT NULL,
    invited_user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    responded_timestamp TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_study_group_invites_group FOREIGN KEY (group_id) REFERENCES study_groups (group_id),
    CONSTRAINT fk_study_group_invites_by_user FOREIGN KEY (invited_by_user_id) REFERENCES users (user_id),
    CONSTRAINT fk_study_group_invites_user FOREIGN KEY (invited_user_id) REFERENCES users (user_id)
);

CREATE INDEX idx_study_group_invites_group ON study_group_invitations (group_id);
CREATE INDEX idx_study_group_invites_user ON study_group_invitations (invited_user_id);
CREATE INDEX idx_study_group_invites_status ON study_group_invitations (status);

CREATE TABLE group_reservations (
    group_reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    booked_by_user_id BIGINT NOT NULL,
    CONSTRAINT fk_group_reservations_reservation FOREIGN KEY (reservation_id) REFERENCES reservations (reservation_id),
    CONSTRAINT fk_group_reservations_group FOREIGN KEY (group_id) REFERENCES study_groups (group_id),
    CONSTRAINT fk_group_reservations_user FOREIGN KEY (booked_by_user_id) REFERENCES users (user_id),
    CONSTRAINT uk_group_reservation_reservation UNIQUE (reservation_id)
);

CREATE INDEX idx_group_reservations_group ON group_reservations (group_id);
